//GET ALL USERS
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTM3OWNmMC02NWJkLTQwMGUtYmNlOS0zYzY2NjQ2YjcxMmQiLCJyb2xlIjoiYnJva2VyIiwiZW1haWwiOiJ0b21pbG9sYUBnbWFpbC5jb20iLCJpYXQiOjE3NDk4ODE4MTcsImV4cCI6MTc0OTk2ODIxN30.NURapNJ80O66VJUCDBQpkFNC0ljHhLAMSMQhU4MD3KY

// GET USER PROFILE
GET http://localhost:4000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTM3OWNmMC02NWJkLTQwMGUtYmNlOS0zYzY2NjQ2YjcxMmQiLCJyb2xlIjoiYnJva2VyIiwiZW1haWwiOiJ0b21pbG9sYUBnbWFpbC5jb20iLCJpYXQiOjE3NDk4ODE4MTcsImV4cCI6MTc0OTk2ODIxN30.NURapNJ80O66VJUCDBQpkFNC0ljHhLAMSMQhU4MD3KY